// Emits the opt-in Quantix pipeline manifest (design section 6.2; plan L2-G).

namespace Quantix.Generator;

/// <summary>
/// Emits the opt-in Quantix pipeline manifest — a human-readable map of every message, its
/// handler(s) and its behavior chain. The manifest is emitted as a comment-only source file, so
/// it has no runtime cost and contributes nothing to the assembly.
/// </summary>
internal static class ManifestEmitter
{
    /// <summary>Emits the pipeline manifest for the given model.</summary>
    /// <param name="model">The resolved Quantix model.</param>
    /// <returns>The manifest as a comment-only C# source file.</returns>
    public static string Emit(QuantixModel model)
    {
        var writer = new CodeWriter();

        writer.Line("// <auto-generated/>");
        writer.Line("//");
        writer.Line("// Quantix pipeline manifest");
        writer.Line("// =========================");
        writer.Line($"// {model.Messages.Count} message(s) discovered in this compilation.");

        for (int i = 0; i < model.Messages.Count; i++)
        {
            EmitMessage(writer, model.Messages[i]);
        }

        return writer.ToString();
    }

    /// <summary>Emits the manifest entry for one message.</summary>
    private static void EmitMessage(CodeWriter writer, MessageModel message)
    {
        writer.Line("//");
        writer.Line($"// {message.MessageType}");
        writer.Line($"//   kind: {DescribeKind(message.Kind, message.ResultType)}");

        if (message.Kind == MessageKind.Notification)
        {
            writer.Line($"//   handlers: {message.Handlers.Count}");
            foreach (string handler in message.Handlers)
            {
                writer.Line($"//     - {handler}");
            }
        }
        else
        {
            writer.Line($"//   handler: {(message.Handlers.Count > 0 ? message.Handlers[0] : "(none)")}");
        }

        if (message.Behaviors.Count > 0)
        {
            writer.Line("//   pipeline (outermost first):");
            foreach (string behavior in message.Behaviors)
            {
                writer.Line($"//     - {behavior}");
            }
        }
    }

    /// <summary>Describes a message kind for the manifest.</summary>
    private static string DescribeKind(MessageKind kind, string? resultType)
        => kind switch
        {
            MessageKind.VoidCommand => "command (no result)",
            MessageKind.Command => $"command -> {resultType}",
            MessageKind.Query => $"query -> {resultType}",
            MessageKind.Notification => "notification",
            MessageKind.StreamRequest => $"stream -> {resultType}",
            _ => "unknown",
        };
}
