// Emits the generated QuantixMediator dispatcher (design section 6, stage 5; plan L2-D, L2-E).

namespace Quantix.Generator;

/// <summary>
/// Emits the generated <c>QuantixMediator</c> — the class that implements <c>Quantix.IMediator</c>
/// in the consuming assembly. Each verb dispatches by message type to a generated <c>Execute</c>
/// method. Routing is adaptive (design section 6.3): a type-pattern chain below the message-count
/// threshold, a <c>FrozenDictionary</c> discriminator with an integer jump-table above it.
/// </summary>
internal static class MediatorEmitter
{
    private const string ValueTask = "global::System.Threading.Tasks.ValueTask";
    private const string CancellationToken = "global::System.Threading.CancellationToken";
    private const string AsyncEnumerable = "global::System.Collections.Generic.IAsyncEnumerable";
    private const string GetRequiredService =
        "global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService";

    /// <summary>
    /// The message count above which the generator switches from a type-pattern chain to the
    /// <c>FrozenDictionary</c> jump-table. Set from the L5-6 benchmark: the type-pattern chain is
    /// faster for average-case routing up to ~32 messages, and the frozen jump-table — flat at
    /// roughly 3.5 ns regardless of count — wins beyond it.
    /// </summary>
    private const int FrozenDispatchThreshold = 32;

    /// <summary>Emits the mediator source for the given model.</summary>
    /// <param name="model">The resolved Quantix model.</param>
    /// <returns>The generated C# source.</returns>
    public static string Emit(QuantixModel model)
    {
        bool frozen = model.Messages.Count > FrozenDispatchThreshold;
        var writer = new CodeWriter();

        writer.Line("// <auto-generated/>");
        writer.Line("#nullable enable");
        writer.Line("#pragma warning disable");
        writer.Line();
        writer.Line($"// Quantix discovered {model.Messages.Count} message(s) in this compilation.");
        writer.Line();
        writer.Line("namespace Quantix.Generated");
        writer.OpenBrace();

        writer.Line("/// <summary>The generated Quantix mediator. This type is generated; do not edit.</summary>");
        writer.Line("internal sealed class QuantixMediator : global::Quantix.IMediator");
        writer.OpenBrace();

        EmitConstructor(writer);
        if (frozen)
        {
            EmitDiscriminatorMap(writer, model);
        }

        EmitSendCommand(writer, model, frozen);
        EmitSendRequest(writer, model, MessageKind.Command, "global::Quantix.ICommand<TResult>", "command", frozen);
        EmitSendRequest(writer, model, MessageKind.Query, "global::Quantix.IQuery<TResult>", "query", frozen);
        EmitPublish(writer, model, frozen);
        EmitStream(writer, model, frozen);
        EmitExecuteMethods(writer, model);

        writer.CloseBrace();
        writer.CloseBrace();

        return writer.ToString();
    }

    /// <summary>Emits the service-provider field and the constructor.</summary>
    private static void EmitConstructor(CodeWriter writer)
    {
        writer.Line("private readonly global::System.IServiceProvider _services;");
        writer.Line();
        writer.Line("/// <summary>Creates the mediator. The service provider resolves handlers and behaviors.</summary>");
        writer.Line("public QuantixMediator(global::System.IServiceProvider services)");
        writer.OpenBrace();
        writer.Line("_services = services;");
        writer.CloseBrace();
    }

    /// <summary>Emits the frozen discriminator map and lookup used by the above-threshold routing.</summary>
    private static void EmitDiscriminatorMap(CodeWriter writer, QuantixModel model)
    {
        writer.Line();
        writer.Line("private static readonly global::System.Collections.Frozen.FrozenDictionary<global::System.Type, int> Discriminators =");
        writer.Line("    global::System.Collections.Frozen.FrozenDictionary.ToFrozenDictionary(");
        writer.Line("        new global::System.Collections.Generic.Dictionary<global::System.Type, int>");
        writer.Line("        {");
        for (int i = 0; i < model.Messages.Count; i++)
        {
            writer.Line($"            {{ typeof({model.Messages[i].MessageType}), {i} }},");
        }

        writer.Line("        });");
        writer.Line();
        writer.Line("/// <summary>Maps a message's runtime type to its dispatch discriminator, or -1.</summary>");
        writer.Line("private static int Discriminator(object message)");
        writer.Line("    => Discriminators.TryGetValue(message.GetType(), out int value) ? value : -1;");
    }

    /// <summary>Emits the void-command Send method.</summary>
    private static void EmitSendCommand(CodeWriter writer, QuantixModel model, bool frozen)
    {
        writer.Line();
        writer.Line($"public {ValueTask} Send(global::Quantix.ICommand command, {CancellationToken} ct = default)");
        writer.OpenBrace();
        EmitRouting(
            writer,
            model,
            MessageKind.VoidCommand,
            "command",
            frozen,
            static (index, message) => $"Execute_{index}({message}, ct)",
            "throw new global::Quantix.QuantixException("
                + "\"No Quantix handler is registered for command type '\" + command.GetType() + \"'.\");");
        writer.CloseBrace();
    }

    /// <summary>Emits a result-returning Send method for commands or queries.</summary>
    private static void EmitSendRequest(
        CodeWriter writer,
        QuantixModel model,
        MessageKind kind,
        string messageInterface,
        string parameterName,
        bool frozen)
    {
        writer.Line();
        writer.Line($"public {ValueTask}<TResult> Send<TResult>({messageInterface} {parameterName}, {CancellationToken} ct = default)");
        writer.OpenBrace();
        EmitRouting(
            writer,
            model,
            kind,
            parameterName,
            frozen,
            static (index, message) => $"({ValueTask}<TResult>)(object)Execute_{index}({message}, ct)",
            $"throw new global::Quantix.QuantixException("
                + $"\"No Quantix handler is registered for {parameterName} type '\" + {parameterName}.GetType() + \"'.\");");
        writer.CloseBrace();
    }

    /// <summary>Emits the Publish method. An unhandled notification is a no-op (design section 8.2).</summary>
    private static void EmitPublish(CodeWriter writer, QuantixModel model, bool frozen)
    {
        writer.Line();
        writer.Line($"public {ValueTask} Publish(global::Quantix.INotification notification, {CancellationToken} ct = default)");
        writer.OpenBrace();
        EmitRouting(
            writer,
            model,
            MessageKind.Notification,
            "notification",
            frozen,
            static (index, message) => $"Execute_{index}({message}, ct)",
            "return default;");
        writer.CloseBrace();
    }

    /// <summary>Emits the Stream method.</summary>
    private static void EmitStream(CodeWriter writer, QuantixModel model, bool frozen)
    {
        writer.Line();
        writer.Line($"public {AsyncEnumerable}<TResult> Stream<TResult>("
            + $"global::Quantix.IStreamRequest<TResult> request, {CancellationToken} ct = default)");
        writer.OpenBrace();
        EmitRouting(
            writer,
            model,
            MessageKind.StreamRequest,
            "request",
            frozen,
            static (index, message) => $"({AsyncEnumerable}<TResult>)(object)Execute_{index}({message}, ct)",
            "throw new global::Quantix.QuantixException("
                + "\"No Quantix handler is registered for stream request type '\" + request.GetType() + \"'.\");");
        writer.CloseBrace();
    }

    /// <summary>
    /// Emits the body of a dispatch verb: routes each message of <paramref name="kind"/> to its
    /// Execute method — a type-pattern chain, or an integer jump-table when <paramref name="frozen"/>
    /// is set — then the miss path.
    /// </summary>
    private static void EmitRouting(
        CodeWriter writer,
        QuantixModel model,
        MessageKind kind,
        string parameterName,
        bool frozen,
        System.Func<int, string, string> callExpression,
        string onMiss)
    {
        if (frozen)
        {
            writer.Line($"switch (Discriminator({parameterName}))");
            writer.OpenBrace();
            for (int i = 0; i < model.Messages.Count; i++)
            {
                if (model.Messages[i].Kind == kind)
                {
                    // The cast goes via 'object' so the compiler accepts it for 'sealed' concrete
                    // message types. A direct cast like ((Msg)command) is rejected as CS0030 when
                    // 'command' is the generic interface ICommand<TResult>/IQuery<TResult>/
                    // IStreamRequest<TResult> and 'Msg' is sealed — the compiler proves no
                    // subclass can ever close the interface differently. The discriminator above
                    // already proved the runtime type, so the through-object cast is sound and,
                    // on reference types, generates the same single 'castclass' IL — zero cost.
                    writer.Line($"case {i}:");
                    writer.Line($"    return {callExpression(i, $"(({model.Messages[i].MessageType})(object){parameterName})")};");
                }
            }

            writer.CloseBrace();
        }
        else
        {
            for (int i = 0; i < model.Messages.Count; i++)
            {
                if (model.Messages[i].Kind == kind)
                {
                    writer.Line($"if ({parameterName} is {model.Messages[i].MessageType} m{i})");
                    writer.OpenBrace();
                    writer.Line($"return {callExpression(i, $"m{i}")};");
                    writer.CloseBrace();
                }
            }
        }

        writer.Line();
        writer.Line(onMiss);
    }

    /// <summary>Emits a private Execute method for every message in the model.</summary>
    private static void EmitExecuteMethods(CodeWriter writer, QuantixModel model)
    {
        for (int i = 0; i < model.Messages.Count; i++)
        {
            MessageModel message = model.Messages[i];
            if (message.Kind == MessageKind.Notification)
            {
                EmitNotificationExecute(writer, i, message);
            }
            else
            {
                EmitExecute(writer, i, message);
            }
        }
    }

    /// <summary>
    /// Emits the strongly-typed dispatch method for one command, query or stream request,
    /// composing the pipeline behavior chain when the message has behaviors.
    /// </summary>
    private static void EmitExecute(CodeWriter writer, int index, MessageModel message)
    {
        string messageType = message.MessageType;
        string resultType = message.ResultType ?? string.Empty;

        string returnType;
        string handlerType;
        string behaviorType;
        string delegateType;

        switch (message.Kind)
        {
            case MessageKind.VoidCommand:
                returnType = ValueTask;
                handlerType = $"global::Quantix.ICommandHandler<{messageType}>";
                behaviorType = $"global::Quantix.ICommandPipelineBehavior<{messageType}>";
                delegateType = "global::Quantix.CommandHandlerDelegate";
                break;
            case MessageKind.Command:
                returnType = $"{ValueTask}<{resultType}>";
                handlerType = $"global::Quantix.ICommandHandler<{messageType}, {resultType}>";
                behaviorType = $"global::Quantix.IPipelineBehavior<{messageType}, {resultType}>";
                delegateType = $"global::Quantix.RequestHandlerDelegate<{resultType}>";
                break;
            case MessageKind.Query:
                returnType = $"{ValueTask}<{resultType}>";
                handlerType = $"global::Quantix.IQueryHandler<{messageType}, {resultType}>";
                behaviorType = $"global::Quantix.IPipelineBehavior<{messageType}, {resultType}>";
                delegateType = $"global::Quantix.RequestHandlerDelegate<{resultType}>";
                break;
            case MessageKind.StreamRequest:
                returnType = $"{AsyncEnumerable}<{resultType}>";
                handlerType = $"global::Quantix.IStreamRequestHandler<{messageType}, {resultType}>";
                behaviorType = $"global::Quantix.IStreamPipelineBehavior<{messageType}, {resultType}>";
                delegateType = $"global::Quantix.StreamHandlerDelegate<{resultType}>";
                break;
            default:
                throw new global::System.InvalidOperationException(
                    "EmitExecute does not handle message kind " + message.Kind + ".");
        }

        writer.Line();
        writer.Line($"private {returnType} Execute_{index}({messageType} message, {CancellationToken} ct)");
        writer.OpenBrace();
        writer.Line($"{handlerType} handler =");
        writer.Line($"    {GetRequiredService}<{message.Handlers[0]}>(_services);");

        int behaviorCount = message.Behaviors.Count;
        if (behaviorCount == 0)
        {
            // Pay-for-play (D15): a message with no behaviors dispatches straight to its handler.
            writer.Line("return handler.Handle(message, ct);");
            writer.CloseBrace();
            return;
        }

        for (int b = 0; b < behaviorCount; b++)
        {
            writer.Line($"{behaviorType} behavior{b} =");
            writer.Line($"    {GetRequiredService}<{message.Behaviors[b]}>(_services);");
        }

        // Compose the chain from the handler outward. Behaviors are ordered outermost-first,
        // so wrap from the innermost behavior towards the outermost.
        writer.Line();
        writer.Line($"{delegateType} next0 =");
        writer.Line("    (token) => handler.Handle(message, token);");

        for (int k = 1; k < behaviorCount; k++)
        {
            writer.Line($"{delegateType} next{k} =");
            writer.Line($"    (token) => behavior{behaviorCount - k}.Handle(message, next{k - 1}, token);");
        }

        // The outermost behavior is invoked directly — it needs no wrapping delegate.
        writer.Line($"return behavior0.Handle(message, next{behaviorCount - 1}, ct);");
        writer.CloseBrace();
    }

    /// <summary>Emits the async dispatch method for one notification: each handler awaited in turn.</summary>
    private static void EmitNotificationExecute(CodeWriter writer, int index, MessageModel message)
    {
        writer.Line();
        writer.Line($"private async {ValueTask} Execute_{index}({message.MessageType} message, {CancellationToken} ct)");
        writer.OpenBrace();

        for (int h = 0; h < message.Handlers.Count; h++)
        {
            writer.Line($"global::Quantix.INotificationHandler<{message.MessageType}> handler{h} =");
            writer.Line($"    {GetRequiredService}<{message.Handlers[h]}>(_services);");
            writer.Line($"await handler{h}.Handle(message, ct).ConfigureAwait(false);");
        }

        writer.CloseBrace();
    }
}
