// Emits the generated AddQuantix registration extension (design section 6, stage 5; plan L2-F).

namespace Quantix.Generator;

/// <summary>
/// Emits the generated <c>AddQuantix</c> extension method — the single call that registers the
/// Quantix mediator, every discovered handler and every pipeline behavior with a
/// dependency-injection container. The extension is emitted <c>internal</c>, so it is callable
/// only from the composition root that generated it and cannot collide across assemblies.
/// </summary>
internal static class RegistrationEmitter
{
    private const string IServiceCollection = "global::Microsoft.Extensions.DependencyInjection.IServiceCollection";
    private const string ServiceDescriptor = "global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor";
    private const string ServiceLifetime = "global::Microsoft.Extensions.DependencyInjection.ServiceLifetime";

    /// <summary>Emits the registration source for the given model.</summary>
    /// <param name="model">The resolved Quantix model.</param>
    /// <returns>The generated C# source.</returns>
    public static string Emit(QuantixModel model)
    {
        var writer = new CodeWriter();

        writer.Line("// <auto-generated/>");
        writer.Line("#nullable enable");
        writer.Line("#pragma warning disable");
        writer.Line();
        writer.Line("namespace Microsoft.Extensions.DependencyInjection");
        writer.OpenBrace();

        writer.Line("/// <summary>Generated Quantix dependency-injection registration. Do not edit.</summary>");
        writer.Line("internal static class QuantixServiceCollectionExtensions");
        writer.OpenBrace();

        EmitAddQuantix(writer, model);

        writer.CloseBrace();
        writer.CloseBrace();

        return writer.ToString();
    }

    /// <summary>Emits the AddQuantix extension method.</summary>
    private static void EmitAddQuantix(CodeWriter writer, QuantixModel model)
    {
        writer.Line("/// <summary>Registers the Quantix mediator, every handler and every behavior.</summary>");
        writer.Line("/// <param name=\"services\">The service collection to add registrations to.</param>");
        writer.Line("/// <param name=\"configure\">An optional callback to configure Quantix options.</param>");
        writer.Line("/// <returns>The same service collection, for chaining.</returns>");
        writer.Line($"internal static {IServiceCollection} AddQuantix(");
        writer.Line($"    this {IServiceCollection} services,");
        writer.Line("    global::System.Action<global::Quantix.QuantixOptions>? configure = null)");
        writer.OpenBrace();

        writer.Line("global::Quantix.QuantixOptions options = new global::Quantix.QuantixOptions();");
        writer.Line("configure?.Invoke(options);");
        writer.Line();
        writer.Line("// The mediator is registered Scoped so it resolves handlers from the caller's scope.");
        writer.Line($"services.Add(new {ServiceDescriptor}(");
        writer.Line("    typeof(global::Quantix.IMediator),");
        writer.Line("    typeof(global::Quantix.Generated.QuantixMediator),");
        writer.Line($"    {ServiceLifetime}.Scoped));");

        EmitClosedTypeRegistrations(writer, Collect(model, static m => m.Handlers), "options.HandlerLifetime");
        EmitClosedTypeRegistrations(writer, Collect(model, static m => m.Behaviors), "options.BehaviorLifetime");

        writer.Line();
        writer.Line("return services;");
        writer.CloseBrace();
    }

    /// <summary>Emits a closed-type self-registration for each type, with the given lifetime expression.</summary>
    private static void EmitClosedTypeRegistrations(CodeWriter writer, List<string> types, string lifetimeExpression)
    {
        foreach (string type in types)
        {
            writer.Line();
            writer.Line($"services.Add(new {ServiceDescriptor}(");
            writer.Line($"    typeof({type}),");
            writer.Line($"    typeof({type}),");
            writer.Line($"    {lifetimeExpression}));");
        }
    }

    /// <summary>Collects the distinct type names from one field of every message, ordered for stable output.</summary>
    private static List<string> Collect(QuantixModel model, Func<MessageModel, EquatableArray<string>> selector)
    {
        var seen = new HashSet<string>(StringComparer.Ordinal);
        var result = new List<string>();

        for (int i = 0; i < model.Messages.Count; i++)
        {
            EquatableArray<string> values = selector(model.Messages[i]);
            for (int j = 0; j < values.Count; j++)
            {
                if (seen.Add(values[j]))
                {
                    result.Add(values[j]);
                }
            }
        }

        result.Sort(StringComparer.Ordinal);
        return result;
    }
}
