// Quantix.IMediator — the single type an application injects (design section 4.3).

namespace Quantix;

/// <summary>
/// Sends commands and queries, publishes notifications, and opens result streams. This is the
/// single Quantix type an application injects.
/// </summary>
/// <remarks>
/// The implementation, <c>QuantixMediator</c>, is generated by the Quantix source generator
/// into the consuming assembly. It performs no runtime reflection: every handler and behavior
/// is reached through generated, strongly-typed code.
/// </remarks>
public interface IMediator
{
    /// <summary>Sends a command that returns no result to its handler.</summary>
    /// <param name="command">The command to send.</param>
    /// <param name="ct">A token that signals a request to cancel the operation.</param>
    /// <returns>A <see cref="System.Threading.Tasks.ValueTask"/> that completes when the command has been handled.</returns>
    ValueTask Send(ICommand command, CancellationToken ct = default);

    /// <summary>Sends a command that returns a result to its handler.</summary>
    /// <typeparam name="TResult">The result type the command produces.</typeparam>
    /// <param name="command">The command to send.</param>
    /// <param name="ct">A token that signals a request to cancel the operation.</param>
    /// <returns>A <see cref="System.Threading.Tasks.ValueTask{TResult}"/> yielding the command's result.</returns>
    ValueTask<TResult> Send<TResult>(ICommand<TResult> command, CancellationToken ct = default);

    /// <summary>Sends a query to its handler.</summary>
    /// <typeparam name="TResult">The result type the query produces.</typeparam>
    /// <param name="query">The query to send.</param>
    /// <param name="ct">A token that signals a request to cancel the operation.</param>
    /// <returns>A <see cref="System.Threading.Tasks.ValueTask{TResult}"/> yielding the query's result.</returns>
    ValueTask<TResult> Send<TResult>(IQuery<TResult> query, CancellationToken ct = default);

    /// <summary>Publishes a notification to every registered handler, sequentially.</summary>
    /// <param name="notification">The notification to publish.</param>
    /// <param name="ct">A token that signals a request to cancel the operation.</param>
    /// <returns>A <see cref="System.Threading.Tasks.ValueTask"/> that completes when every handler has run.</returns>
    ValueTask Publish(INotification notification, CancellationToken ct = default);

    /// <summary>Opens an asynchronous stream of results produced by a stream request.</summary>
    /// <typeparam name="TResult">The type of each item in the stream.</typeparam>
    /// <param name="request">The stream request to send.</param>
    /// <param name="ct">A token that signals a request to cancel the enumeration.</param>
    /// <returns>An <see cref="System.Collections.Generic.IAsyncEnumerable{T}"/> of results.</returns>
    IAsyncEnumerable<TResult> Stream<TResult>(IStreamRequest<TResult> request, CancellationToken ct = default);
}
